### ISSUE TITLE
Mobile navbar behavior

### ISSUE THREAD

**Issue by sachaw** [samuelhorn/jamdocs#11]
On mobile devices, the navbar noes not behave correctly:

![image](https://user-images.githubusercontent.com/11172820/75427925-47566700-5997-11ea-899d-7c73b8ec6912.png)
![image](https://user-images.githubusercontent.com/11172820/75427944-4f160b80-5997-11ea-8f4c-fe471fe2b5a2.png)

The page body should not be visible, and the close button should be located on the sidebar.

**Comment by samuelhorn** [comment]
Hi, thanks for the feedback!

In fact, in this design the body should still be visible. But you should still be able to see the close icon like in my example. Do it disappear when you open the menu? Which device and browser version are you using?

![IMG_4040](https://user-images.githubusercontent.com/2532266/75459354-8c6e9f00-597f-11ea-89af-e37c5f2ef4cc.PNG)

**Comment by samuelhorn** [comment]
Hi, thanks for the feedback!

In fact, in this design the body should still be visible. But you should still be able to see the close icon like in my example. Do it disappear when you open the menu? Which device and browser version are you using?

![IMG_4040](https://user-images.githubusercontent.com/2532266/75459354-8c6e9f00-597f-11ea-89af-e37c5f2ef4cc.PNG)

**Comment by sachaw** [comment]
I was just guessing at the intended design, as for the devices/browsers:

I have tries, my phone (Oneplus One) with chrome,
Also have tried using chrome desktop using the device simulator.

All of these were done to your demo.

**Comment by samuelhorn** [comment]
Thank you again. This bug is now fixed! 122f5e6f6f34ff1a0f6314378a6be9fc15bead87
