### ISSUE TITLE
[enhancement] Ability to download docs as a PDF

### ISSUE THREAD

**Issue by liambarr** [samuelhorn/jamdocs#13]
Would be great if the docs could be exported as a PDF (or icml file for use in InDesign)

**Comment by samuelhorn** [comment]
Do you mean like download each page as pdf, or the whole docs? I guess one page would be pretty easy with a js lib like html2pdf.

**Comment by liambarr** [comment]
I was thinking all docs, however I’ve just come across [Pandoc](https://github.com/jgm/pandoc), which might be better for my case anyway as I could then style it in another program.

**Comment by samuelhorn** [comment]
Cool. I will close this for now then!
