### ISSUE TITLE
Active subtopic "dot" not highlighting last active subtopic if topics are h3

### ISSUE THREAD

**Issue by dkhunt27** [samuelhorn/jamdocs#15]
In the documentation, I think it says the sidebar will build links/refs to all h2 (or ## in MD); however, it is building links to all h2-h6 items in my MD file. Not sure if that might be the underlying issue.

The little green dot correctly highlights the active subtopic in the MD when it is an h2; however, it doesn't correctly highlight the the right subtopic when it is an h3 or h4... assuming same for h5.h6... when that topic is the last one... it highlights the one above.

So if I have 4 h3 headings called A,B,C,D.  If I click on A, B, or C... the little green dot works correctly...however, if I click on D, then the little green dot is on C.

**Comment by dkhunt27** [comment]
Now noticing that sometimes it does work, sometimes not.  Seems to not highlight the correct "last" one when the scrollbar is all the way at the bottom when jumping to the anchor.

**Comment by samuelhorn** [comment]
Will fix this as soon as I can!
