### ISSUE TITLE
Algolia search

### ISSUE THREAD

**Issue by aloisdg** [samuelhorn/jamdocs#26]
Hello,

I am looking to use jamdocs. For my usecase, the Algolia search would be needed in the long run.
When do you plan to start this feature? Is there anything I can do to give a hand.
Great work on jamdocs! Thank you :)

Link that could be useful: https://www.stackbit.com/blog/gatsby-search/ (Algolia with Gatsby though)

Cheers,

**Comment by samuelhorn** [comment]
Hi! For now I have been busy building my personal site. But now i hope to fix most of the issues here on Jamdocs. Im afraid Algolia isnt at the top of the list though, but if anyone else want to add it Im happy to accept a PR. Sorry I cant promise a date when I have time to do it, but hopefully in a couple of weeks from now!

**Comment by aloisdg** [comment]
No problem! This is a free open source software, you dont have to promise anything if you dont want to ^^
I may look into it later on. Have a nice day

**Comment by aloisdg** [comment]
I will close this issue for now.
