### ISSUE TITLE
Dark theme by default

### ISSUE THREAD

**Issue by mrbenosborne** [samuelhorn/jamdocs#33]
Might be a silly question but is there any way to have the dark theme as the default?

**Comment by samuelhorn** [comment]
Try changing line 32 & 33 in this file:
`jamdocs/src/components/ThemeSwitch.vue`

From:
```
localStorage.setItem('theme', 'bright')
self.theme = 'bright'
```
To:
```
localStorage.setItem('theme', ’dark')
self.theme = ’dark'
```

**Comment by mrbenosborne** [comment]
Great that seemed to work! Thanks :+1:
