### ISSUE TITLE
Ability to edit everything in Forestry

### ISSUE THREAD

**Issue by samuelhorn** [samuelhorn/jamdocs#9]
Would be great if one could edit the front page for Jamdocs on Forestry as well, just like you edit the menu and doc-pages. 

Any ideas @DirtyF? 🤔

**Comment by DirtyF** [comment]
Forestry can mainly edit front matter, Markdown and JSON files. 
Youl can insert Vue components in the Markdown Editor (Prosemirror). 
See https://github.com/DirtyF/portfolio-vuepress/blob/master/portfolio/index.md for a basic example with VuePress.
With first-gen SSG that only rely on front matter, I would have suggested [blocks](https://forestry.io/docs/settings/fields/blocks/), but I'm guessin you want to use components here. 

P.S: our team is currently working on[Tina](https://tinacms.org), more in phase with new-gen SSGs, Tina provide components and blocks, but there's no Vue or Gridsome plugins for now.

**Comment by samuelhorn** [comment]
Thanks!

Im subscribed for Tina since I saw the presentation. Hoping it will be implemented in Vue and Svelte as well.

So, i guess the front page for Jamdocs has to be a Markdown file, and the "teasers" made as Vue-components in that markdown file.

Will experiment with it!
